export function getDummyFollows() {
  const now = Date.now();
  const iso = (minsAgo: number) => new Date(now - minsAgo * 60_000).toISOString();

  return [
    {
      id: 101,
      status: "active",
      market: "FOREX",
      requestedAt: iso(220),
      approvedAt: iso(200),
      masterId: 9001,
      followerTradingAccountId: 50011,
      riskMode: "multiplier",
      riskValue: 1.5,
      maxLot: 2,
      maxOpenPositions: 10,
      maxDailyLoss: 250,
      slippageTolerance: 0.3,
      symbolWhitelist: ["EURUSD", "GBPUSD", "XAUUSD"],
      master: {
        accountLabel: "MT5 • Primary FX Master",
        accountMeta: { mt5LoginId: "12345678", server: "ICMarketsSC-Live", env: "live" },
        brokerName: "MT5",
      },
    },
    {
      id: 102,
      status: "paused",
      market: "FOREX",
      requestedAt: iso(180),
      approvedAt: iso(170),
      masterId: 9002,
      followerTradingAccountId: 50012,
      riskMode: "fixed_lot",
      riskValue: 0.1,
      maxLot: 1,
      maxOpenPositions: 6,
      maxDailyLoss: 180,
      slippageTolerance: 0.2,
      symbolWhitelist: ["EURUSD", "USDJPY"],
      master: {
        accountLabel: "cTrader • Alpha",
        accountMeta: { ctraderAccountId: "45697822", environment: "live" },
        brokerName: "cTrader",
      },
    },

    {
      id: 201,
      status: "active",
      market: "INDIAN",
      requestedAt: iso(90),
      approvedAt: iso(80),
      masterId: 9101,
      followerTradingAccountId: 51001,
      riskMode: "fixed_risk_pct",
      riskValue: 1,
      maxLot: 10,
      maxOpenPositions: 12,
      maxDailyLoss: 1500,
      slippageTolerance: 0.05,
      symbolWhitelist: ["NIFTY", "BANKNIFTY", "RELIANCE"],
      master: {
        accountLabel: "Kite • Zerodha Master",
        accountMeta: { kiteClientId: "AB1234", exchange: "NSE" },
        brokerName: "kite",
      },
    },
    {
      id: 202,
      status: "pending",
      market: "INDIAN",
      requestedAt: iso(40),
      approvedAt: null,
      masterId: 9102,
      followerTradingAccountId: 51002,
      riskMode: "multiplier",
      riskValue: 1.2,
      maxLot: 8,
      maxOpenPositions: 8,
      maxDailyLoss: 1200,
      slippageTolerance: 0.08,
      symbolWhitelist: ["SBIN", "HDFCBANK"],
      master: {
        accountLabel: "Zebu • Swing",
        accountMeta: { zebuClientId: "ZEBU-7788", product: "MIS" },
        brokerName: "zebu",
      },
    },

    {
      id: 301,
      status: "active",
      market: "CRYPTO",
      requestedAt: iso(30),
      approvedAt: iso(25),
      masterId: 9201,
      followerTradingAccountId: 52001,
      riskMode: "multiplier",
      riskValue: 2,
      maxLot: 5,
      maxOpenPositions: 15,
      maxDailyLoss: 350,
      slippageTolerance: 0.15,
      symbolWhitelist: ["BTCUSDT", "ETHUSDT", "SOLUSDT"],
      master: {
        accountLabel: "Binance • Futures Master",
        accountMeta: { exchange: "Binance", subAccount: "global-master-1" },
        brokerName: "binance",
      },
    },
  ];
}
